name: Selenium Cucumber TestNG Workflow
on:
   workflow_dispatch:
 # push:
 #   branches:
 #     - main
 # pull_request:
 #   branches:
 #     - main
jobs:
 test:
   runs-on: windows-latest
   steps:
   # Checkout the repository
   - name: Checkout Code
     uses: actions/checkout@v3
   # Set up Java
   - name: Set up JDK
     uses: actions/setup-java@v3
     with:
       distribution: 'temurin'
       java-version: '11' # Update to your required Java version
   # Cache Maven dependencies
   - name: Cache Maven dependencies
     uses: actions/cache@v3
     with:
       path: ~/.m2/repository
       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
       restore-keys: |
         ${{ runner.os }}-maven-
   # Install Maven dependencies
   - name: Install Maven dependencies
     run: mvn clean install -DskipTests=true
   # Run Cucumber tests
   - name: Run Tests
     run: mvn test
   # Upload test reports as artifacts
   - name: Upload Test Reports
     if: always() # Always upload reports even if tests fail
     uses: actions/upload-artifact@v3
     with:
       name: test-reports
       path: target/cucumber-reports # Adjust to your report location

 
   - name: Deploy to GitHub Pages
     if: always()
     env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
     run: |
        echo "Using GITHUB_TOKEN: $GITHUB_TOKEN"
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git checkout --orphan gh-pages
        git reset --hard
        cp -r target/cucumber-reports/* .
        git add .
        git commit -m 'Deploy test report'
        git push --force "https://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@github.com/GolfWC/oneDataTravel_Automation.git" gh-pages     
